spring:
  application:
    name: spring_ecommerce_inventory
  datasource:
    url: jdbc:mysql://localhost:3306/spring_ecommerce_inventory?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082